Disable start execution button if job is already started
statisticsnorway/dapla-tsquare pull request #6
Opened 2020-10-07 16:10 UTC by takvamborgen

2020-10-07 16:29 UTC, hadrienk approved these changes

2020-10-08 07:52 UTC, hadrienk requested changes

2020-10-08 07:52 UTC, hadrienk commented on src/components/Notebooks.js
> +    setChecked(checkedNotebooks);
Is this to set the state on first render? 
If so you can replace the `[]` by `checkedNotebooks` in the `useState()`

2020-10-08 07:52 UTC, hadrienk commented on src/components/Executions.js
> +        data = response.data
Is it safe to update the data variable?
if `loading || updateLoading || error || updateError` is false then `(updateData || data).jobs.map(job => job.notebook.id)` should hold.

2020-10-08 07:52 UTC, hadrienk commented on src/components/Executions.js
> +      data = response.data
Same here

2020-10-08 07:52 UTC, hadrienk commented on src/components/Notebooks.js
> +const makeHierarchy = (notebooks, created, updated, showCheckboxes) => {
Not worth changing ATM, but I think the best here would be to save the node values in the tree and then make other passes to setup label and showCheckbox.

2020-10-08 07:54 UTC, takvamborgen commented on src/components/Notebooks.js
> +    setChecked(checkedNotebooks);
It is both to set on first render and to check dependent notebooks. Setting it in `useState()` only helps with first render.

2020-10-08 08:22 UTC, takvamborgen commented on src/components/Executions.js
> +        data = response.data
It is not necessary to update the data variable here. Removing it.

2020-10-08 08:59 UTC, merged